name: schembl_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - intel-openmp=2019.4
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.17.3
  - numpy-base=1.17.3
  - openssl=1.1.1d
  - pandas=0.25.2
  - pip=19.3.1
  - python=3.7.5
  - python-dateutil=2.8.0
  - pytz=2019.3
  - readline=7.0
  - setuptools=41.6.0
  - six=1.12.0
  - sqlalchemy=1.3.10
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11

